---
on:
  push: {}
  workflow_dispatch: {}
permissions:
  contents: read
  packages: write
jobs:
  iso:
    uses: BobyMCbobs/ublue-os-isogenerator/.github/workflows/iso.yml@242ed7baebd8d219420d7e7417f7bd56aa9b5060 # TODO revert when merged
    with:
      ARCH: x86_64
      IMAGE_NAME: image
      IMAGE_REPO: ghcr.io/ii
      IMAGE_TAG: latest
      VARIANT: Silverblue
      VERSION: 39
      WEB_UI: false
