---
on:
  push: {}
  workflow_dispatch: {}
permissions:
  contents: read
  packages: write
jobs:
  iso:
    runs-on: ubuntu-latest
    container:
      image: fedora:39
      options: --privileged
      volumes:
        - /:/host
    steps:
      - uses: actions/checkout@473055ba18d6d2da209cd46110aadb9275e3194e
      - uses: ublue-os/isogenerator@a8cdedd915546b69c1e76036f85759b1f35cd029
        with:
          ARCH: x86_64
          IMAGE_NAME: image
          IMAGE_REPO: ghcr.io/ii
          IMAGE_TAG: latest
          VARIANT: Silverblue
          VERSION: 39
          WEB_UI: false
          ACTION_REPO: ublue-os/isogenerator
          ACTION_REF: a8cdedd915546b69c1e76036f85759b1f35cd029
